#!/bin/sh
# Not using any more, just left here so I won't have to figure out how to do
# this again if I ever wanted to.

usage() {
    >&2 echo "usage: $0 {playpause|next|prev|play|pause}"
}

if [ $# -ne 1 ]; then
    usage
    exit 1
fi

case $1 in
    help)
        usage;;
    playpause)
        cmd="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause"
        ;;
    next)
        cmd="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next"
        ;;
    prev)
        cmd="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous"
        ;;
    play)
        cmd="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play"
        ;;
    pause)
        cmd="dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause"
        ;;
    *)
        usage
        exit 1
esac

>&2 echo "$cmd"
$cmd
